### ISSUE TITLE
Eliminar la posibilidad de que dos samples del mismo grupo suenen a la vez.

### ISSUE THREAD

**Issue by mi-mina** [antropoloops/app#9]
(Le he puesto el label de keyboard porque creo que es ahí donde se podría gesionar esto, pero no estoy segura)

Ahora mismo seguimos la limitación autoimpuesta de que sólo puedan sonar hasta 8 cosas a la vez. A nivel de sonido remezclar más de ocho cosas parace complicado. Eso implica que si tenemos más de 8 samples, hay samples que están en el mismo grupo y que no deberían poder sonar a la vez (lo que ocurre de forma automática cuando pones dos clips en el mismo track en Ableton).

**Comment by danigb** [comment]
Implementado (dentro de audio-playback/polyphony). Ahora mismo sólo puede sonar un clip por track,  pero será configurable.
